services:
  casper-nctl-2-docker-1.5.8:
    image: casper-nctl-2-docker-1.5.8:latest
    container_name: casper-nctl-2-docker-1.5.8
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["1.5.8"]
    build:
      args:
        - BRANCH_NODE=v1.5.8
        - BRANCH_CLIENT=v2.0.0

  casper-nctl-2-docker-stable:
    image: casper-nctl-2-docker-stable:latest
    container_name: casper-nctl-2-docker-stable
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["stable"]
    build:
      args:
        - BRANCH_NODE=v2.2.2
        - BRANCH_CLIENT=v5.0.1
        - BRANCH_SIDECAR=v2.1.0

  casper-nctl-2-docker-2.0:
    image: casper-nctl-2-docker-2.0:latest
    container_name: casper-nctl-2-docker-2.0
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["2.0"]
    build:
      args:
        - BRANCH_NODE=v2.0.4
        - BRANCH_CLIENT=v5.0.0
        - BRANCH_SIDECAR=v2.0.0

  casper-nctl-2-docker-2.1:
    image: casper-nctl-2-docker-2.1:latest
    container_name: casper-nctl-2-docker-2.1
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["2.1"]
    build:
      args:
        - BRANCH_NODE=v2.1.2
        - BRANCH_CLIENT=v5.0.0
        - BRANCH_SIDECAR=v2.0.0

  casper-nctl-2-docker-2.2:
    image: casper-nctl-2-docker-2.2:latest
    container_name: casper-nctl-2-docker-2.2
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["2.2"]
    build:
      args:
        - BRANCH_NODE=v2.2.2
        - BRANCH_CLIENT=v5.0.1
        - BRANCH_SIDECAR=v2.1.0

  casper-nctl-2-docker-dev:
    image: casper-nctl-2-docker-dev:latest
    container_name: casper-nctl-2-docker-dev
    extends:
      service: casper-nctl-2-docker
      file: common-service.yml
    profiles: ["dev"]
    build:
      args:
        - BRANCH_NODE=dev
        - BRANCH_CLIENT=dev
        - BRANCH_SIDECAR=dev

  cors-anywhere:
    container_name: cors-anywhere
    profiles: ["cors-anywhere"]
    build:
      context: ./cors
      dockerfile: cors-anywhere.Dockerfile
    tty: true
    environment:
      PORT: 11100
    ports:
      - 11100:11100
