services:
  casper-nctl-2-docker:
    container_name: casper-nctl-2-docker
    image: casper-nctl-2-docker:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BRANCH_NODE: v1.5.8
        BRANCH_CLIENT: v2.0.0
    ports:
      - 11101-11105:11101-11105
      - 14101-14105:14101-14105
      - 18101-18105:18101-18105
      - 25101-25105:25101-25105
      - 28101-28105:28101-28105
    volumes:
      - ${NCTL_HOST_ROOT:-${PWD}}/assets/faucet:/app/casper-nctl/assets/net-1/faucet/
      - ${NCTL_HOST_ROOT:-${PWD}}/assets/users:/app/casper-nctl/assets/net-1/users/
      - ${NCTL_HOST_ROOT:-${PWD}}/assets/chainspec:/app/casper-nctl/assets/net-1/chainspec/
      - ${NCTL_HOST_ROOT:-${PWD}}/assets/nodes:/app/casper-nctl/assets/net-1/nodes/
