name: CI/CD Image 2.2

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/*.md"
      - "**/*.mdc"
      - "docs/**"
      - "mkdocs.yml"
      - "LICENSE"
      - "CHANGELOG.md"

jobs:
  nightly-build-push-2-2:
    name: Build and Push Docker Image 2.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for 2.2
        run: |
          make build 2.2
          docker tag casper-nctl-2-docker-2.2 ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:2.2
          docker tag casper-nctl-2-docker-2.2 ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:stable
          docker tag casper-nctl-2-docker-2.2 ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:latest
          docker tag casper-nctl-2-docker-2.2 interchouette/casper-nctl-2-docker:2.2
          docker tag casper-nctl-2-docker-2.2 interchouette/casper-nctl-2-docker:stable
          docker tag casper-nctl-2-docker-2.2 interchouette/casper-nctl-2-docker:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:2.2
          docker push ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:stable
          docker push ${{ secrets.DOCKER_USERNAME }}/casper-nctl-2-docker:latest
          docker push interchouette/casper-nctl-2-docker:2.2
          docker push interchouette/casper-nctl-2-docker:stable
          docker push interchouette/casper-nctl-2-docker:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Tag Docker image for 2.2
        run: |
          docker tag casper-nctl-2-docker-2.2 ghcr.io/groussac/casper-nctl-2-docker:2.2
          docker tag casper-nctl-2-docker-2.2 ghcr.io/groussac/casper-nctl-2-docker:stable
          docker tag casper-nctl-2-docker-2.2 ghcr.io/groussac/casper-nctl-2-docker:latest
          docker tag casper-nctl-2-docker-2.2 ghcr.io/interchouette-itc/casper-nctl-2-docker:2.2
          docker tag casper-nctl-2-docker-2.2 ghcr.io/interchouette-itc/casper-nctl-2-docker:stable
          docker tag casper-nctl-2-docker-2.2 ghcr.io/interchouette-itc/casper-nctl-2-docker:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/groussac/casper-nctl-2-docker:2.2
          docker push ghcr.io/groussac/casper-nctl-2-docker:stable
          docker push ghcr.io/groussac/casper-nctl-2-docker:latest
          docker push ghcr.io/interchouette-itc/casper-nctl-2-docker:2.2
          docker push ghcr.io/interchouette-itc/casper-nctl-2-docker:stable
          docker push ghcr.io/interchouette-itc/casper-nctl-2-docker:latest
